### ISSUE TITLE
What I need to put in upload_file_path parameter [help wanted].

### ISSUE THREAD

**Issue by dasoga** [peartherapeutics/bitrise-aws-device-farm-file-deploy#15]
Hi,

Basically I need help because I don't know what path I need to put in the parameter
`upload_file_path`

Thank you

**Comment by dasoga** [comment]
I discovered I used this env variable:
`$BITRISE_IPA_PATH`

Now I got and error upload failed, but I'll check what is it.

Thanks

**Comment by markhu** [comment]
Actually, I think this step is for uploading test scripts, not IPA or APK binaries. I think the testable binaries are uploaded in the `bitrise-aws-device-farm-runner` step.

Related to #17 docs clarification request.

**Comment by Sean12oshea** [comment]
@markhu I think you're right. Finally got `bitrise-aws-device-farm-runner` working once I removed `bitrise-aws-device-farm-file-deploy`. Any chance you know how to set the username and password for an Android explorer test which you can see [here](https://docs.aws.amazon.com/devicefarm/latest/developerguide/test-types-built-in-explorer.html)? `bitrise-aws-device-farm-runner` lets you set the test type to `BUILTIN_EXPLORER` but thats it.

**Comment by fadookie** [comment]
@Sean12oshea This would be [a parameter you pass to the test run](https://docs.aws.amazon.com/devicefarm/latest/APIReference/API_ScheduleRunTest.html) so it would definitely need to be be handled by `bitrise-aws-device-farm-runner`.  I believe these would need to be specified in the `parameters` object [which currently is not configurable](https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/blob/master/step.sh#L223). I don't have time to work on this right now but I would be open to a backwards-compatible PR that allows these fields to be set.
